version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - cd backend
      - npm install
  pre_build:
    commands:
      - echo "Start testing..."
      # Discover and run unit tests in the 'tests' directory
      - npm test
    finally:
      - echo "Finish testing..."
  post_build:
    commands:
      # Remove existing node_modules to clear dev dependencies
      - rm -r node_modules

      # Install runtime dependencies
      - npm install --production
      
artifacts:
  files:
    - README.md
    - appspec.yml
    - scripts/*
    - backend/**/*
    