version: 0.2
env:
  variables:
    REACT_APP_BACKEND_URL: https://blog.backend.jimkk159.com
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - cd frontend
      - npm install
  build:
    commands:
      - echo "Start building..."
      # Build react project
      - npm run build
    finally:
      - echo "Finish building..."
  post_build:
    commands:
      - echo "Updating files in the S3 bucet..."
      - aws s3 sync build s3://jim-blog-frontend --delete
      