name: backend code unit test

on: [pull_request, push]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy: 
      matrix: 
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: list folder
        run: ls -a
      - name: change folder
        run: cd backend
      - name: npm install
        run: npm ci
      - name: test
        run: npm test